apiVersion: v1
kind: Pod
metadata:
   name: nodeapp
   labels:
     app: nodeapp
spec:
  containers:
  - name: nodeapp
    image: pallavink/2022cfse034-docker-ecr-img
    ports:
     - containerPort: 8080
