# Generated by Django 4.1.7 on 2023-05-21 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microapp', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
